language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - if [ "$TRAVIS_BRANCH" = "production" ]; then export PUBLIC_URL=https://preview.edopportunity.org/explorer/; fi
  - if [ "$TRAVIS_BRANCH" = "staging" ]; then export PUBLIC_URL=https://staging.edopportunity.org/explorer/; fi
  - npm run build
before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
deploy:
  - skip_cleanup: true
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: edop-explorer-staging
    region: us-east-1
    acl: public_read
    local_dir: build
    upload-dir: explorer
    on:
      branch: staging
  - provider: script
    script: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID_STAGING --paths="/explorer/*"
    on:
      branch: staging
  - skip_cleanup: true
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: edop-explorer-production
    region: us-east-1
    acl: public_read
    local_dir: build
    upload-dir: explorer
    on:
      branch: production
  - provider: script
    script: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID_PRODUCTION --paths="/explorer/*"
    on:
      branch: production
